---
- hosts: kali 
  become: yes
  roles:
    - kali_customizations
  vars_files:
    - vars/vars.yml
    - vars/users.yml
    
- hosts: docker
  become: yes
  roles:
    - docker
  vars_files:
    - vars/vars.yml
    - vars/users.yml