---
- hosts: target
  roles:
    - common
    - target_customizations
  vars_files:
    - vars/vars.yml
- hosts: kali 
  become: yes
  roles:
    - kali_customizations
  vars_files:
    - vars/vars.yml
