---
# need to wrap an if statement around this one
# make it windows specific
- name : Disable Windows Firewall
  win_firewall:
          state: disabled
- include: windows-disable-defender.yml
  when: ansible_distribution is search ('Microsoft')
- include: chocolatey-components.yml
