---
- name: Get python3 going
  raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3-minimal)

- name: Get python3 pip
  raw: test -e /usr/bin/pip3 || (apt -y update && apt install -y python3-pip)
  
- name: Make python3 default
  alternatives:
     name: python
     path: /usr/bin/python3
     link: /usr/bin/python
     priority: 10

- name: Remove old docker versions
  apt:
    name: "{{kali.uninstall_items}}"
    state: absent

- name: Install required system packages
  apt:
    name: "{{kali.install_items}}"
    update_cache: yes
    state: present

- name: Add Docker GPG apt key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker Repo
  apt_repository:
    repo: deb https://download.docker.com/linux/debian buster stable
    state: present

- name: Update apt and install docker-ce
  apt:
    update_cache: yes
    name: docker-ce
    state: latest

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.28.4/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'

- name: Add kali user to group
  user: 
    name: ubuntu
    groups: [docker]
    append: yes

- name: Change ExecStart
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: Copy new docker daemon
  copy:
     src: override.conf
     dest: /etc/systemd/system/docker.service.d/override.conf

- name: Requirement to re-reload the system daemon process
  raw: "systemctl daemon-reload"

- name: Hack to restart Docker manually because system-reload changed
  raw: "systemctl restart docker"

- name: Create the directory for Targets
  ansible.builtin.file:
    path: /home/ubuntu/targets
    state: directory

- name: Synchronize folders 
  copy:
    src: ../../../../targets/
    dest: /home/ubuntu/targets

- name: Build Containers
  raw: "cd /home/ubuntu/targets; docker-compose build"

- name: Start containers\
  raw: "cd /home/ubuntu/targets; docker-compose up -d"

- name: Pause for Containers....
  pause:
    seconds: 30

- name: Check that you can connect (GET) to a page and it returns a status 200
  uri:
    url: http://localhost

