---
- name: Install Chocolately via Powershell
  win_shell: "Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex
"
- name: Install notepadplusplus
  win_chocolatey:
    name: notepadplusplus
